steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg BUILD_SECRET="$$BUILD_SECRET" \
          -t gcr.io/$PROJECT_ID/jibhong-website \
          .
    secretEnv: ['BUILD_SECRET']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jibhong-website']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'jibhong-website'
      - '--image=gcr.io/$PROJECT_ID/jibhong-website'
      - '--region=asia-southeast1'

availableSecrets:
  secretManager:
    - versionName: projects/983966396927/secrets/jibhong-website-secret/versions/latest
      env: 'BUILD_SECRET'