options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -n "$$BUILD_SECRET" ]; then
          echo "BUILD_SECRET length: ${#BUILD_SECRET}"
        else
          echo "BUILD_SECRET is not set or empty"
        fi

        docker build \
          --build-arg BUILD_SECRET="$$BUILD_SECRET" \
          -t asia-southeast1-docker.pkg.dev/$PROJECT_ID/portfolio-website-registry/jibhong-website:$COMMIT_SHA \
          .
    secretEnv: ['BUILD_SECRET']
    
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg BUILD_SECRET="$$BUILD_SECRET" \
          -t asia-southeast1-docker.pkg.dev/$PROJECT_ID/portfolio-website-registry/jibhong-website:$COMMIT_SHA \
          .
    secretEnv: ['BUILD_SECRET']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/portfolio-website-registry/jibhong-website:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "$BRANCH_NAME" == "main" ]; then
          echo "Branch is $BRANCH_NAME. Deploying to PRODUCTION..."
          gcloud run deploy jibhong-portfolio-website \
            --image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/portfolio-website-registry/jibhong-website:$COMMIT_SHA \
            --region=asia-southeast1
        else
          echo "Branch is $BRANCH_NAME. Deploying to STAGING..."
          gcloud run deploy jibhong-portfolio-staging \
            --image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/portfolio-website-registry/jibhong-website:$COMMIT_SHA \
            --region=asia-southeast1
        fi

availableSecrets:
  secretManager:
    - versionName: projects/983966396927/secrets/jibhong-website-secret/versions/latest
      env: 'BUILD_SECRET'